<a href="https://colab.research.google.com/github/tanuunakal/LIHTC_research/blob/main/analyzing_all_states_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TLDR: Preminary Analysis (How careful do we have to be using this databse?)

### Glossary:

**Project**: each row has information about an entire project, when we say project we mean data from a row.

### Analysis questions:
1. **Do all the projects have a state assigned to them?**
   Yes

2. **Does an entire column have data missing?** No

3. **Does a certain state have data missing for an entire column?** Yes. refer cell: https://colab.research.google.com/drive/1m1NSBVgvEIhuQ1xGl38X-dDi0LHXXMWp#scrollTo=6N56qrEs4_N2

4. **Year discrepancies:** The application year for certain projects is a weird number like 8888 or out of the normal year range (1980s - 2020s)

5. Certain years have a lot more data than some other years.

In [1]:
from tqdm import tqdm
import pandas as pd
from openpyxl import load_workbook
from io import BytesIO
import urllib
import warnings
import json
import re
from google.colab import drive
warnings.filterwarnings("ignore")
#!pip install google-auth
from google.colab import auth
auth.authenticate_user()  # must authenticate

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
df = pd.read_csv('/content/drive/MyDrive/lihtc/LIHTCPUB.CSV')
df

,hud_id,project,proj_add,proj_cty,proj_st,proj_zip,state_id,latitude,longitude,place1990,...,n_unitsr,li_unitr,metro,dda,qct,nonprog,nlm_reason,nlm_spc,datanote,record_stat
0,AKA0000X034,YENLO PHASE I AND II,402-451 NORTH YENLO STREET,WASILLA,AK,99654,AK-99-99,61.583094,-149.437633,NaN,...,37.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X
1,AKA19890010,PARK WEST APTS,2012 SANDVIK ST,FAIRBANKS,AK,99709,AK-89-00001,64.851646,-147.803418,1080.0,...,83.0,81.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,X
2,AKA19900005,TYSON'S TERRACE,103 BURKHART DR,SITKA,AK,99835,AK-90-00001,57.048874,-135.303021,3040.0,...,16.0,16.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,X
3,AKA19910005,NORTHWOOD APTS,190 PARKWOOD CIR,SOLDOTNA,AK,99669,AK-91-00001,60.489146,-151.073858,2810.0,...,23.0,22.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,X
4,AKA19930005,CHINOOK VILLA,1200 S CENTURY CIR,WASILLA,AK,99654,AK-93-00001,61.569852,-149.449509,NaN,...,32.0,31.0,2.0,0.0,2.0,NaN,NaN,NaN,NaN,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53027,WYA20210002,FREESTONE APARTMENTS,2173 W HARRISON STREET,LARAMIE,WY,82070,WY-19-697,41.307671,-105.625759,NaN,...,36.0,36.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,X
53028,WYA20210003,PLATTE RIVER APARTMENTS,800 W. RICHARDS STREET,DOUGLAS,WY,82633,WY-20-710,42.751085,-105.397488,NaN,...,20.0,20.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,X
53029,WYA20220001,CODY SENIOR,2102 PIONEER AVE,CODY,WY,82414,WY-20-709,44.530798,-109.048527,NaN,...,24.0,24.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,N
53030,WYA20220002,MEADOWLARK VISTA,4400 S. COFFMAN AVE.,CASPER,WY,82604,WY-19-698,42.806996,-106.346962,NaN,...,49.0,48.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,N
53031,WYA20220003,PIONEER VILLAGE,2301 PIONEER AVE,CODY,WY,82414,WY-20-722,44.531063,-109.045669,NaN,...,24.0,23.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,N

In [7]:
# @title ### All the projects that do not have a state assigned to them
df[df['proj_st'].isna()]

Empty DataFrame
Columns: [hud_id, project, proj_add, proj_cty, proj_st, proj_zip, state_id, latitude, longitude, place1990, place2000, place2010, place2020, fips1990, fips2000, fips2010, fips2020, scattered_site_cd, resyndication_cd, allocamt, n_units, li_units, n_0br, n_1br, n_2br, n_3br, n_4br, inc_ceil, low_ceil, ceilunit, yr_pis, yr_alloc, non_prof, basis, bond, mff_ra, fmha_514, fmha_515, fmha_538, home, home_amt, tcap, tcap_amt, cdbg, cdbg_amt, htf, htf_amt, fha, hopevi, hpvi_amt, tcep, tcep_amt, rad, qozf, qozf_amt, rentassist, trgt_pop, trgt_fam, trgt_eld, trgt_dis, trgt_hml, trgt_other, trgt_spc, type, credit, n_unitsr, li_unitr, metro, dda, qct, nonprog, nlm_reason, nlm_spc, datanote, record_stat]
Index: []

[0 rows x 75 columns]

In [9]:
#@title ### Projects grouped by state and year
df_by_state_year = df.groupby(['proj_st', 'yr_pis']).size().reset_index(name='count')
df_by_state_year = df_by_state_year.sort_values(by='count', ascending=False).reset_index(drop=True)
df_by_state_year

     proj_st  yr_pis  count
0         TX    8888    452
1         NY    8888    423
2         NJ    2012    264
3         CA    2014    253
4         MA    8888    225
...      ...     ...    ...
1909      NM    2016      1
1910      NM    2014      1
1911      DC    2022      1
1912      MT    1990      1
1913      AK    1989      1

[1914 rows x 3 columns]

In [11]:
#@title ### Does an entire column have data missing?
missing_columns = df.columns[df.isna().all()]

print("Columns that have missing data are: ")
for col in missing_columns:
    print(col)

Columns that have missing data are:

In [16]:
#@title ### Does a certain state have data missing for an entire column?

groups = df.groupby('proj_st')
filtered_df = pd.DataFrame()

column_names = df.columns
mapping_group_empty_columns = {}

# Loop through each group and filter rows where any column is NaN
for name, group in groups:
  empty_columns = []

  for column in column_names:
    if group[column].isna().all():
      empty_columns.append(column)

  mapping_group_empty_columns[name] = empty_columns

# Display the filtered DataFrame
print(mapping_group_empty_columns)

{'AK': ['nonprog', 'nlm_reason', 'nlm_spc'], 'AL': ['nlm_spc'], 'AR': ['htf', 'rad', 'qozf', 'nlm_reason', 'nlm_spc'], 'AS': ['place1990', 'place2000', 'place2010', 'place2020', 'resyndication_cd', 'allocamt', 'n_0br', 'n_1br', 'n_2br', 'n_3br', 'n_4br', 'inc_ceil', 'low_ceil', 'ceilunit', 'non_prof', 'basis', 'htf', 'htf_amt', 'rad', 'qozf', 'qozf_amt', 'trgt_fam', 'trgt_eld', 'trgt_dis', 'trgt_hml', 'trgt_other', 'trgt_spc', 'nonprog', 'nlm_reason', 'nlm_spc'], 'AZ': ['nlm_spc'], 'CA': ['nlm_reason', 'nlm_spc'], 'CO': [], 'CT': ['nlm_reason', 'nlm_spc'], 'DC': ['nlm_reason', 'nlm_spc'], 'DE': ['resyndication_cd', 'mff_ra', 'tcap', 'htf', 'rad', 'qozf', 'trgt_spc', 'nlm_reason', 'nlm_spc'], 'FL': ['nlm_spc'], 'GA': ['nlm_spc'], 'GU': ['place1990', 'place2000', 'place2010', 'nonprog', 'nlm_reason', 'nlm_spc', 'datanote'], 'HI': ['fmha_538', 'trgt_spc', 'nlm_spc'], 'IA': ['nlm_spc'], 'ID': ['nlm_spc'], 'IL': ['nlm_spc'], 'IN': ['fmha_514', 'fmha_538', 'hopevi', 'nlm_reason', 'nlm_spc'], 'KS': ['trgt_spc', 'nlm_spc'], 'KY': ['nlm_spc'], 'LA': ['mff_ra', 'tcap', 'htf', 'qozf'], 'MA': ['nonprog', 'nlm_reason', 'nlm_spc'], 'MD': ['nlm_reason', 'nlm_spc'], 'ME': ['nlm_reason', 'nlm_spc'], 'MI': [], 'MN': ['nlm_reason', 'nlm_spc'], 'MO': ['nlm_spc'], 'MP': ['place1990', 'place2000', 'place2010', 'place2020', 'nonprog', 'nlm_reason', 'nlm_spc', 'datanote'], 'MS': ['nlm_spc'], 'MT': ['nlm_reason', 'nlm_spc'], 'NC': ['qozf', 'trgt_spc', 'nlm_spc'], 'ND': [], 'NE': ['nlm_spc'], 'NH': ['nlm_spc'], 'NJ': ['trgt_spc', 'nlm_reason', 'nlm_spc'], 'NM': ['place2020', 'htf', 'htf_amt', 'rad', 'qozf', 'qozf_amt', 'nonprog', 'nlm_reason', 'nlm_spc'], 'NV': ['nlm_reason', 'nlm_spc'], 'NY': ['nlm_spc'], 'OH': ['rad', 'qozf', 'nlm_reason', 'nlm_spc'], 'OK': ['nlm_spc'], 'OR': ['nlm_reason', 'nlm_spc'], 'PA': ['rad', 'qozf', 'nlm_spc'], 'PR': ['place1990', 'nlm_reason', 'nlm_spc'], 'RI': ['trgt_spc', 'nlm_reason', 'nlm_spc'], 'SC': ['nlm_reason', 'nlm_spc'], 'SD': ['trgt_spc', 'nlm_reason', 'nlm_spc'], 'TN': ['nlm_reason', 'nlm_spc'], 'TX': ['qozf', 'nlm_spc'], 'UT': ['nlm_spc'], 'VA': ['trgt_spc', 'nlm_reason', 'nlm_spc'], 'VI': ['place1990', 'place2000', 'place2010', 'place2020', 'resyndication_cd', 'tcap', 'htf', 'htf_amt', 'rad', 'qozf', 'qozf_amt', 'trgt_spc', 'nlm_reason', 'nlm_spc'], 'VT': [], 'WA': ['htf', 'rad', 'qozf', 'nlm_reason', 'nlm_spc'], 'WI': ['fmha_514', 'fmha_538', 'htf', 'hopevi', 'tcep', 'rad', 'qozf', 'trgt_spc', 'nlm_spc'], 'WV': ['nlm_spc'], 'WY': ['resyndication_cd', 'htf', 'rad', 'qozf', 'trgt_spc', 'nlm_spc']}